const DATABASE_NAME = '@infoChampions';

const COLLECTION_USERS = `${DATABASE_NAME}:user`;
const COLLECTION_FAVORITES= `${DATABASE_NAME}:favorites`;

export {
  COLLECTION_USERS,
  COLLECTION_FAVORITES
}